// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtDDFREkF6CVZ2S1J6oj_4T1MlsT-twVk',
    appId: '1:788356763678:web:0da7a4e75ef4a3ca811e0f',
    messagingSenderId: '788356763678',
    projectId: 'androidbookproject-3e666',
    authDomain: 'androidbookproject-3e666.firebaseapp.com',
    storageBucket: 'androidbookproject-3e666.firebasestorage.app',
    measurementId: 'G-6TNJ0WW1TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5M3Lxe-QLXmDFYQV2UBmfKahgHi--iBk',
    appId: '1:788356763678:android:985d8c62f86143ed811e0f',
    messagingSenderId: '788356763678',
    projectId: 'androidbookproject-3e666',
    storageBucket: 'androidbookproject-3e666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzF6nxIKsHRTd8XaAGMlBsv8abNy-dO7I',
    appId: '1:788356763678:ios:f5139f58795a775d811e0f',
    messagingSenderId: '788356763678',
    projectId: 'androidbookproject-3e666',
    storageBucket: 'androidbookproject-3e666.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzF6nxIKsHRTd8XaAGMlBsv8abNy-dO7I',
    appId: '1:788356763678:ios:f5139f58795a775d811e0f',
    messagingSenderId: '788356763678',
    projectId: 'androidbookproject-3e666',
    storageBucket: 'androidbookproject-3e666.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtDDFREkF6CVZ2S1J6oj_4T1MlsT-twVk',
    appId: '1:788356763678:web:b9ddfb694442a2da811e0f',
    messagingSenderId: '788356763678',
    projectId: 'androidbookproject-3e666',
    authDomain: 'androidbookproject-3e666.firebaseapp.com',
    storageBucket: 'androidbookproject-3e666.firebasestorage.app',
    measurementId: 'G-PKRWY071ZN',
  );
}
