// Core Flutter UI framework
import 'package:flutter/material.dart';

// Firebase initialization package
import 'package:firebase_core/firebase_core.dart';

// Your Firebase configuration file (generated by Firebase CLI)
import 'firebase_options.dart';

// Import all the screens used in the app
import 'screens/age_selection_screen.dart';
import 'screens/books_0_4_screen.dart';
import 'screens/books_4_8_screen.dart';
import 'screens/books_8_12_screen.dart';
import 'screens/upload_book_screen.dart';

/// The main function that runs the Flutter app.
/// It also ensures Firebase is initialized before the app starts.
void main() async {
  // Required when using async code before runApp()
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the configuration from firebase_options.dart
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Start the app
  runApp(const MyApp());
}

/// The root widget of the app
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Removes the DEBUG banner in the corner
      debugShowCheckedModeBanner: false,

      // App name
      title: 'Kids Book App',

      // Theme configuration: colors, fonts, button styles, etc.
      theme: ThemeData(
        primarySwatch: Colors.deepPurple,                // App bar and primary color
        scaffoldBackgroundColor: Colors.white,           // White background for all pages

        // Default font styles used across the app
        textTheme: const TextTheme(
          titleLarge: TextStyle(fontSize: 28, fontWeight: FontWeight.bold), // Large titles
          bodyMedium: TextStyle(fontSize: 18),                               // Normal text
        ),

        // Default style for all ElevatedButtons
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            padding: const EdgeInsets.symmetric(vertical: 16),  // Vertical padding
            textStyle: const TextStyle(fontSize: 20),            // Font size
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.all(Radius.circular(12)), // Rounded corners
            ),
            backgroundColor: Colors.deepPurple,  // Button background color
            foregroundColor: Colors.white,       // Button text color
          ),
        ),
      ),

      // The first screen to show when the app starts
      initialRoute: '/',

      // Named routes for easy navigation between screens
      routes: {
        '/': (context) => const AgeSelectionScreen(),  // Main menu screen
        '/books_0_4': (context) => const Books04Screen(),     // 0–4 age group
        '/books_4_8': (context) => const Books48Screen(),     // 4–8 age group
        '/books_8_12': (context) => const Books812Screen(),   // 8–12 age group
        '/upload': (context) => const UploadBookScreen(),     // Upload book form
      },
    );
  }
}
